# Prometheus configuration for Federated AI Sentinel

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'federated-ai-sentinel'

# Scrape configurations
scrape_configs:
  # FastAPI metrics
  - job_name: 'infection-risk-api'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

# Alerting rules (optional)
# rule_files:
#   - 'alert_rules.yml'

